[package]
name = "AdventOfCode2025"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
nom = "8.0.0"

[dev-dependencies]
pretty_assertions = { version = "1.4.1", features = ["alloc", "unstable"] }
